### ISSUE TITLE
Fastlane Bloc release 2.7.2 2fa issue

### ISSUE THREAD

**Issue by arthursady** [bitrise-steplib/steps-fastlane#66] opened 2021-01-13 11:54 UTC
Hey guys, since yesterday I believe because of release 2.7.2 all my flows that run fastlane match are breaking.

These are the two changes release 2.7.2 mentions: 

Validate Apple Developer Connection (expiry).
Expose FASTLANE_SESSION only for the fastlane command.

In order to validate this, I rolled the blocs on my workflows to version 2.6.x and in this case they start working again, so I do think there is something out of place with version 2.7.2. Was it expected to stop working with the 2fa account setup on bitrise?

**Comment by godrei** [comment] 2021-01-13 12:26
Hi @arthursady could you please share a failing build URL?

**Comment by arthursady** [comment] 2021-01-13 14:17
@godrei https://app.bitrise.io/build/4056d65caae73a34#?tab=log

This is a link of a build that was failing with the bloc 2.7.2 and worked with the rebuild button once I changed to version 2.6.x

**Comment by godrei** [comment] 2021-01-13 14:54
@arthursady could you please also share the latest working build url (using step version 2.6.x)?

**Comment by arthursady** [comment] 2021-01-14 17:55
@godrei sorry for the delay. https://app.bitrise.io/build/a0a38173255d1ecd#?tab=log this is the build after.

**Comment by godrei** [comment] 2021-01-15 09:18
Hi @arthursady,
huge thanks for your help!

Unfortunately, we introduced a bug in version 2.7.2, details can be found here: https://github.com/bitrise-steplib/steps-fastlane/pull/68.
The issue is fixed in version [2.7.4](https://github.com/bitrise-steplib/steps-fastlane/releases/tag/2.7.4).

I'll close this issue, but if you need more info/help just open a new issue!

**Closed as completed by godrei** 2021-01-15 09:18 UTC
