### ISSUE TITLE
Could not create the Java Virtual Machine

### ISSUE THREAD

**Issue by seka** [bitrise-steplib/steps-fastlane#63] opened 2020-10-09 20:36 UTC
There's an error with iTMSTransporter.

```
[18:48:48]: -------------------
[18:48:48]: --- Step: pilot ---
[18:48:48]: -------------------
[18:48:48]: Login to App Store Connect (hoge-huga@example.com)
[18:48:50]: Login successful
[18:48:52]: Ready to upload new build to TestFlight (App:xxxxxxxxxx)...
[18:48:54]: Going to upload updated app to App Store Connect
[18:48:54]: This might take a few minutes. Please don't interrupt the script.
[18:48:54]: [iTMSTransporter] -Djava.ext.dirs=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext is not supported.  Use -classpath instead.
[18:48:54]: [iTMSTransporter] Error: Could not create the Java Virtual Machine.
[18:48:54]: [iTMSTransporter] Error: A fatal exception has occurred. Program will exit.
[18:48:54]: iTunes Transporter output above ^
[18:48:54]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+--------------------+--------------------------------------------------------------------------------------------------+
|                                                     Lane Context                                                      |
+--------------------+--------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                                              |
| PLATFORM_NAME      | ios                                                                                              |
| LANE_NAME          | ios upload_testflight                                                                            |
| IPA_OUTPUT_PATH    | /Users/vagrant/git/build/my-sample-app.ipa                                                             |
| XCODEBUILD_ARCHIVE | /Users/vagrant/Library/Developer/Xcode/Archives/2020-10-09/my-sample-app 2020-10-09 18.34.24.xcarchive |
| DSYM_OUTPUT_PATH   | /Users/vagrant/git/build/my-sample-app.app.dSYM.zip                                                    |
+--------------------+--------------------------------------------------------------------------------------------------+
[18:48:54]: Error uploading ipa file, for more information see above
+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | cocoapods                  | 8           |
| 4    | gym                        | 888         |
| 💥   | pilot                      | 6           |
+------+----------------------------+-------------+
[18:48:54]: fastlane finished with errors
[!] Error uploading ipa file, for more information see above
#######################################################################
# fastlane 2.162.0 is available. You are on 2.148.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
Fastlane command: (bundle "_2.1.4_" "exec" "fastlane" "ios" "upload_testflight") failed
If you want to send an issue report to fastlane (https://github.com/fastlane/fastlane/issues/new), you can find the output of fastlane env in the following log file:
/Users/vagrant/deploy/fastlane_env.log
Command failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | fastlane@2.7 (exit code: 1)                                   | 15.9 min |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-fastlane/issues           |
| Source: https://github.com/bitrise-io/steps-fastlane                         |
+---+---------------------------------------------------------------+----------+
```

So, I debug with ssh.

```
$ ssh -o StrictHostKeyChecking=no vagrant@3.tcp.ngrok.io -p 24096
vagrant@prd-atl-std-r-xcode-12-201009180416-zhkuGWY4sYPEEwftpdjSy6 ~ % ls /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext
ls: /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext: No such file or directory
```

What should I do?

**Comment by bitce** [comment] 2020-10-13 13:59
Hi @seka! Can you please send us a build URL and enable support user access in the Settings?

**Comment by michaeldiguiseppi** [comment] 2020-10-28 21:40
https://github.com/fastlane/fastlane/pull/16689 Looks like steps-fastlane needs to pull in these changes to enable support for Xcode versions > Xcode 11? @bitce We just encountered this issue when updating to Xcode 12 in our project.

**Comment by bitce** [comment] 2020-10-29 08:15
Hi @michaeldiguiseppi! Do you experience this issue even when opting for the latest fastlane version? If so, can you please send us a build URL here?

**Comment by michaeldiguiseppi** [comment] 2020-10-29 15:45
https://app.bitrise.io/build/f4d3be810249e0d5#?tab=log.  This was one that failed. However for the time being our workaround is to replace the pilot step with the xcrun altool step, which seems to work properly with Xcode 12.

**Comment by bitce** [comment] 2020-10-30 09:44
That's correct! The other step does not use fastlane so it shouldn't be affected. Strangely I can't seem to find the logs for this build. Can you enable Support User access for us?

**Comment by seka** [comment] 2020-12-07 03:06
Maybe... I need to review the handling of 2FA. I'll try the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` settings.
but, an issue that is of concern here.
https://discuss.bitrise.io/t/bitrise-repeatedly-asking-2factor-authentication-on-fastlane-actions/13992

**Comment by bitce** [comment] 2020-12-07 10:27
Hi @seka! What is the problem you're seeing exactly? Can you brief us into it and/or send me a build URL?

**Comment by seka** [comment] 2020-12-09 03:51
Sorry... Cannot be published build URL because it's not my personal project.
I saved `FASTLANE_PASSWORD`, `FASTLANE_SESSION`, `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` in secret environment variables. but, Pilot asks for 2FA.
I replaced steps-fastlane to steps-script. So, pilot works fine.

**Comment by bitce** [comment] 2020-12-09 09:49
Sure, as you wish. Just for transparency, the URL would allow us access to metadata about the build (when was it started, by who, how, in what environment) and the build logs themselves. 
 I believe the `FASTLANE_SESSION` variable does not get automatically created due to an ongoing issue, so that is likely the cause I suppose, won't be able to tell for sure.

**Comment by ZedFergusApp** [comment] 2021-01-11 23:22
We are having the exact same errors.

Can you have a look and help us.

Our build url is https://app.bitrise.io/build/d348c221d0062f4b#?tab=log

Thanks so much.

**Comment by ZedFergusApp** [comment] 2021-01-14 04:29
Anyone can look into this issue? It happens on Xcode 12 setup, and is really blocking our pipeline.

**Comment by cathyharmon** [comment] 2021-01-19 16:54
Hello,

We have recently made changes in this area.  If you are still having problems, please open a support ticket.  Please be sure to include the build url and enable support access.  You can enable support access under the "Settings" tab for the app.

Thanks

**Comment by alexviquez** [comment] 2021-05-01 04:42
I have the same issue about iTMSTransporter, the fastlane action is from pilot, and the problem was change the xcode version to 12, currently iOS does not allow compiling in previous versions!

**Comment by mohamed461994** [comment] 2021-05-06 02:51
I have the same issue since moved from Xcode 11 to 12.

**Comment by lpusok** [comment] 2021-05-10 15:16
Hello @alexviquez @mohamed461994 @ZedFergusApp @seka @michaeldiguiseppi!
Can you please confirm that you are using Fastlane  2.182.0 (the latest one).

If your project doesn't contain a fastlane gem in your project's Gemfile, you can use the input **Should update fastlane gem before run**. Set this input to `true` so that the Step can install the latest fastlane version to your project.
If a gem lockfile (*Gemfile.lock* or gems.locked) includes the fastlane gem in the working directory, that specific fastlane version will be installed. In that case please update your gems (`bundle update`)

In case you are having issues with the `FASTLANE_SESSION` or other authentication related issue, please refer to https://devcenter.bitrise.io/getting-started/connecting-to-services/configuring-bitrise-steps-that-require-apple-developer-account-data/. API key authentication is a newer option that does not require 2FA and it is less likely to stop working.

Please let me know if this does not solve your problems or contact https://www.bitrise.io/bitrise-support.

**Comment by lpusok** [comment] 2021-06-17 08:50
Closing due to inactivity. Please open a new issue if needed.

**Closed as completed by lpusok** 2021-06-17 08:50 UTC
