### ISSUE TITLE
Fastlane version detection in Gemfile.lock bug / not correct

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-steplib/steps-fastlane#31] opened 2017-11-14 14:59 UTC
From a related build's log:

```
+------------------------------------------------------------------------------+
| (4) fastlane                                                                 |
+------------------------------------------------------------------------------+
| id: fastlane                                                                 |
| version: 2.3.9                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-11-14T05:31:39-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
[36mINFO[0m[05:31:39]  * [32;1m[OK][0m Step dependency (go) installed, available. 

[34;1mConfigs:[0m
- WorkDir: 
- Lane: something
- UpdateFastlane: true

[34;1mExpand WorkDir[0m
WorkDir not set, using CurrentWorkingDirectory...
[32;1mExpanded WorkDir: /Users/vagrant/git[0m

[34;1mDetermine desired Fastlane version[0m
Checking Gemfile.lock (/Users/vagrant/git/Gemfile.lock) for fastlane gem
Gemfile.lock defined fastlane version: 4.4.5
```

So it thinks fastlane version in Gemfile.lock is `4.4.5`, but fastlane is at v2 right now, there's no v4 yet.

In fact, when it does a `bundle install` and then checks the version that's the correct version:

```
[34;1mFastlane version:[0m
[32;1m$ bundle "exec" "fastlane" "--version"[0m
fastlane installation at path:
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.64.1/bin/fastlane
-----------------------------
fastlane 2.64.1
```

**Comment by kdobmayer** [comment] 2018-01-08 09:30
Hi @viktorbenei ,

Thanks for the report. The issue is fixed in version release [2.3.12](https://github.com/bitrise-io/steps-fastlane/releases/tag/2.3.12). I will close this issue, if you need any more help just let us know.

**Closed as completed by kdobmayer** 2018-01-08 09:30 UTC
Labels: bug
